### ISSUE TITLE
InboxZero shows extra line

### ISSUE THREAD

**Issue by rollecode** [jpminor/mailspring-isaac-light-theme#1]
Hello! I love your theme both on my Windows PC and Macbook. I archive every handled mail so I noticed when threads are empty, I see empty line:

![Screenshot](https://i.imgur.com/PSvUvhI.png "Screenshot")

Easy fix would be something like:

```` css
.list-rows:empty {
	display: none;
}
````
